- repo: https://github.com/prettier/prettier
  rev: master
  hooks:
    - id: prettier
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: go-mod-tidy
