version: 2.1

orbs:
  node: circleci/node@3.0

executors:
  go-exec:
    description: |
      "The official CircleCI Go Docker image on Docker Hub.
      Found here: https://hub.docker.com/r/cimg/go"
    docker:
      - image: cimg/go:1.14
    environment:
      GOPATH: /home/circleci/go
  golangci-lint:
    description: |
      "Go linters runnner."
    docker:
      - image: golangci/golangci-lint:v1.27.0

commands:
  load-source-cache:
    description: Load chached source codes.
    steps:
      - restore_cache:
          keys:
            - source-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - source-{{ .Environment.CACHE_VERSION }}-

  save-source-cache:
    description: Save chached source codes.
    steps:
      - save_cache:
          key: source-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

jobs:
  prepare_source:
    executor: go-exec
    steps:
      - load-source-cache
      - checkout
      - save-source-cache

  unit_test:
    executor: go-exec
    steps:
      - load-source-cache
      - checkout
      - run:
          command: make test_unit
          name: exec unit test

  intergration_test:
    executor: go-exec
    steps:
      - load-source-cache
      - checkout
      - run:
          command: make test_intergration
          name: exec intergration test

  go_lint:
    executor: golangci-lint
    steps:
      - load-source-cache
      - checkout
      - run:
          name: exec go lint
          command: make lint_go

  md_lint:
    executor: node/default
    steps:
      - load-source-cache
      - checkout
      - node/install-packages:
          cache-version: v1
          cache-path: ~/.npm
          with-cache: true
      - run:
          name: exec markdown lint
          command: make lint_md

workflows:
  check_code:
    jobs:
      - prepare_source
      - unit_test:
          requires:
            - prepare_source
      - intergration_test:
          requires:
            - prepare_source
      - go_lint:
          requires:
            - prepare_source
      - md_lint:
          requires:
            - prepare_source
