version: 2.1

executors:
  go-exec:
    description: |
      "The official CircleCI Go Docker image on Docker Hub.
      Found here: https://hub.docker.com/r/cimg/go"
    docker:
      - image: cimg/go:1.14
    environment:
      GOPATH: /home/circleci/go
  golangci-lint:
    description: |
      "Go linters runnner."
    docker:
      - image: golangci/golangci-lint:v1.27.0

commands:
  load-source-cache:
    description: Load chached source codes.
    steps:
      - restore_cache:
          keys:
            - source-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - source-{{ .Environment.CACHE_VERSION }}-

  save-source-cache:
    description: Save chached source codes.
    steps:
      - save_cache:
          key: source-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  load-go-cache:
    description: Load chached go modules.
    steps:
      - restore_cache:
          keys:
            - go-{{ .Environment.CACHE_VERSION }}-{{ checksum "go.sum" }}
            - go-{{ .Environment.CACHE_VERSION }}-

  save-go-cache:
    description: Save go modules to cache.
    steps:
      - save_cache:
          paths:
            - /home/circleci/go/pkg/mod
          key: go-{{ .Environment.CACHE_VERSION }}-{{ checksum "go.sum" }}

  go-mod-download:
     description: Run 'go mod download'.
     steps:
       - run:
           command: go mod download
           name: go mod download.

  go-mod-download-cache:
     description: Load chache and Download  Go modules.
     steps:
       - load-go-cache
       - go-mod-download

jobs:
  prepare_source:
    executor: go-exec
    steps:
      - load-source-cache
      - checkout
      - save-source-cache
      # Comment out because it takes more time to cache.
      # - go-mod-download-cache
      # - save-go-cache

  unit_test:
    executor: go-exec
    steps:
      - load-source-cache
      - checkout
      # - go-mod-download-cache
      - run:
          command: make test/unit
          name: exec unit test

  intergration_test:
    executor: go-exec
    steps:
      - load-source-cache
      - checkout
      - run:
          command: make test/intergration
          name: exec intergration test

  go_lint:
    executor: golangci-lint
    steps:
      - load-source-cache
      - checkout
      - run:
          name: exec golangci-lint
          command: |
            golangci-lint run ./... --disable-all \
            -E govet -E errcheck -E staticcheck -E unused -E gosimple \
            -E structcheck -E varcheck -E ineffassign -E deadcode -E typecheck \
            -E golint -E interfacer -E unconvert -E dupl -E goconst \
            -E asciicheck -E gofmt -E goimports -E misspell -E lll -E unparam \
            -E prealloc -E gocritic -E gochecknoinits -E whitespace -E gomnd \
            -E goerr113 -E gomodguard -E godot -E testpackage

workflows:
  check_code:
    jobs:
      - prepare_source
      - unit_test:
          requires:
            - prepare_source
      - intergration_test:
          requires:
            - prepare_source
      - go_lint:
          requires:
            - prepare_source
